# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Workspace Manager sidecar."""

import sys
from pathlib import Path

block_cipher = None

# Collect all service modules
service_modules = [
    'sidecar.services.claude_service',
    'sidecar.services.config_service',
    'sidecar.services.hierarchy',
    'sidecar.services.terminal_service',
    'sidecar.services.session_history',
    'sidecar.services.propagation',
    'sidecar.services.promotion',
    'sidecar.services.toggle_service',
    'sidecar.services.file_browser',
    'sidecar.services.template_service',
    'sidecar.services.scope_service',
    'sidecar.services.memory_service',
    'sidecar.services.commands_service',
    'sidecar.services.hooks_service',
    'sidecar.services.permissions_service',
    'sidecar.services.agents_service',
    'sidecar.services.claude_settings_service',
    'sidecar.services.skills_service',
    'sidecar.services.knowledge_service',
    'sidecar.services.personality_service',
    'sidecar.services.brand_context_service',
    'sidecar.services.claudemd_generator',
    'sidecar.services.session_memory_service',
    'sidecar.services.learnings_service',
    'sidecar.services.scheduler_service',
    'sidecar.services.onboarding_service',
    'sidecar.services.watcher_service',
    'sidecar.services.service_registry',
    'sidecar.services.reconciliation_service',
    # Activation & health (claudectx integration)
    'sidecar.services.safe_io',
    'sidecar.services.activation',
    'sidecar.services.health',
    'sidecar.services.workspace_bundle',
]

a = Analysis(
    ['src/sidecar/main.py'],
    pathex=[],
    binaries=[],
    datas=[('../packs', 'packs')],
    hiddenimports=[
        # FastAPI / Starlette / Uvicorn internals
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'starlette.responses',
        'sse_starlette',
        'sse_starlette.sse',
        # Pydantic
        'pydantic',
        'pydantic.deprecated',
        'pydantic.deprecated.decorator',
        # PyWinPTY
        'winpty',
        # Service modules
        *service_modules,
        # Sidecar core
        'sidecar.models',
        'sidecar.parsers',
        'sidecar.schemas',
        # Router modules
        'sidecar.routers.analytics',
        'sidecar.routers.profiles',
        'sidecar.routers.hierarchy',
        'sidecar.routers.chat',
        'sidecar.routers.terminal',
        'sidecar.routers.propagation',
        'sidecar.routers.promotion',
        'sidecar.routers.toggles',
        'sidecar.routers.files',
        'sidecar.routers.templates',
        'sidecar.routers.sessions',
        'sidecar.routers.settings',
        'sidecar.routers.patterns',
        'sidecar.routers.config',
        'sidecar.routers.memory',
        'sidecar.routers.commands',
        'sidecar.routers.hooks',
        'sidecar.routers.permissions',
        'sidecar.routers.agents',
        'sidecar.routers.claude_settings',
        'sidecar.routers.skills',
        'sidecar.routers.knowledge',
        'sidecar.routers.personality',
        'sidecar.routers.brand_context',
        'sidecar.routers.claudemd',
        'sidecar.routers.session_memory',
        'sidecar.routers.learnings',
        'sidecar.routers.scheduler',
        'sidecar.routers.onboarding',
        'sidecar.routers.watcher',
        'sidecar.routers.reconciliation',
        # Activation & health routers (claudectx integration)
        'sidecar.routers.activation',
        'sidecar.routers.health_check',
        'sidecar.routers.bundle',
        # MCP server modules
        'sidecar.mcp_server',
        'sidecar.mcp_server.__main__',
        'sidecar.mcp_server.config',
        'sidecar.mcp_server.discovery',
        'sidecar.mcp_server.server',
        'sidecar.mcp_server.tools',
        'sidecar.mcp_server.tools.read_tools',
        'sidecar.mcp_server.tools.write_tools',
        'sidecar.mcp_server.tools.activation_tools',
        'sidecar.mcp_server.utils',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='sidecar',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Tauri reads stdout/stderr
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
