// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomProvider(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddCustomProvider'](arg1, arg2, arg3, arg4, arg5);
}

export function Apply(arg1) {
  return window['go']['main']['App']['Apply'](arg1);
}

export function BaseFolders(arg1) {
  return window['go']['main']['App']['BaseFolders'](arg1);
}

export function BundledTQPath() {
  return window['go']['main']['App']['BundledTQPath']();
}

export function DefaultBase() {
  return window['go']['main']['App']['DefaultBase']();
}

export function DetectShells() {
  return window['go']['main']['App']['DetectShells']();
}

export function Doctor() {
  return window['go']['main']['App']['Doctor']();
}

export function ExistingWorkspaces() {
  return window['go']['main']['App']['ExistingWorkspaces']();
}

export function HooksStatus() {
  return window['go']['main']['App']['HooksStatus']();
}

export function InstallTQ(arg1) {
  return window['go']['main']['App']['InstallTQ'](arg1);
}

export function LoginCommand(arg1, arg2) {
  return window['go']['main']['App']['LoginCommand'](arg1, arg2);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function Preview(arg1) {
  return window['go']['main']['App']['Preview'](arg1);
}

export function Providers() {
  return window['go']['main']['App']['Providers']();
}

export function TQVersion() {
  return window['go']['main']['App']['TQVersion']();
}

export function ToolCheck(arg1) {
  return window['go']['main']['App']['ToolCheck'](arg1);
}

export function ValidatePlan(arg1) {
  return window['go']['main']['App']['ValidatePlan'](arg1);
}
