// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {setupapi} from '../models';

export function AddCustomProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<string, string>):Promise<string>;

export function Apply(arg1:setupapi.Plan):Promise<setupapi.Report>;

export function BaseFolders(arg1:string):Promise<Array<setupapi.FolderCandidate>>;

export function BundledTQPath():Promise<string>;

export function DefaultBase():Promise<string>;

export function DetectShells():Promise<Array<string>>;

export function Doctor():Promise<Array<setupapi.Finding>>;

export function ExistingWorkspaces():Promise<Array<setupapi.Workspace>>;

export function HooksStatus():Promise<Array<setupapi.HookStatus>>;

export function InstallTQ(arg1:string):Promise<string>;

export function LoginCommand(arg1:string,arg2:string):Promise<string>;

export function OpenTerminal(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function Preview(arg1:setupapi.Plan):Promise<Array<setupapi.Change>>;

export function Providers():Promise<Array<setupapi.Provider>>;

export function TQVersion():Promise<string>;

export function ToolCheck(arg1:setupapi.Plan):Promise<Record<string, Array<setupapi.ToolResult>>>;

export function ValidatePlan(arg1:setupapi.Plan):Promise<void>;
